package com.frenchcoder.scalamones.elastic

import spray.json._

object ClusterStat {
  case class ClusterStatIndicesShardsIndexShards(min: Int, max: Int, avg: Double)
  case class ClusterStatIndicesShardsIndexPrimaries(min: Int, max: Int, avg: Double)
  case class ClusterStatIndicesShardsIndexReplication(min: Int, max: Int, avg: Double)
  case class ClusterStatIndicesShardsIndex(shards: ClusterStatIndicesShardsIndexShards, primaries: ClusterStatIndicesShardsIndexPrimaries, replication: ClusterStatIndicesShardsIndexReplication)
  case class ClusterStatIndicesShards(total: Int, primaries: Int, replication: Double, index: ClusterStatIndicesShardsIndex)
  case class ClusterStatIndicesFilterCache(memory_size_in_bytes: Int, evictions: Int)
  case class ClusterStatIndicesIdCache(memory_size_in_bytes: Int)
  case class ClusterStatIndicesDocs(count: Int, deleted: Int)
  case class ClusterStatIndicesCompletion(size_in_bytes: Int)
  case class ClusterStatIndicesStore(size_in_bytes: Int, throttle_time_in_millis: Int)
  case class ClusterStatIndicesPercolate(queries: Int, memory_size_in_bytes: Int, total: Int, memory_size: String, current: Int, time_in_millis: Int)
  case class ClusterStatIndicesSegments(count: Int, version_map_memory_in_bytes: Int, index_writer_max_memory_in_bytes: Int, fixed_bit_set_memory_in_bytes: Int, memory_in_bytes: Int, index_writer_memory_in_bytes: Int)
  case class ClusterStatIndicesFielddata(memory_size_in_bytes: Int, evictions: Int)
  case class ClusterStatIndices(shards: ClusterStatIndicesShards, count: Int, filter_cache: ClusterStatIndicesFilterCache, id_cache: ClusterStatIndicesIdCache, docs: ClusterStatIndicesDocs, completion: ClusterStatIndicesCompletion, store: ClusterStatIndicesStore, percolate: ClusterStatIndicesPercolate, segments: ClusterStatIndicesSegments, fielddata: ClusterStatIndicesFielddata)
  case class ClusterStatNodesJvmVersions(count: Int, vm_name: String, vm_vendor: String, version: String, vm_version: String)
  case class ClusterStatNodesJvmMem(heap_used_in_bytes: Long, heap_max_in_bytes: Long)
  case class ClusterStatNodesJvm(max_uptime_in_millis: Int, versions: Array[ClusterStatNodesJvmVersions], mem: ClusterStatNodesJvmMem, threads: Int)
  case class ClusterStatNodesCount(master_only: Int, master_data: Int, total: Int, client: Int, data_only: Int)
  case class ClusterStatNodesPlugins(jvm: Boolean, name: String, url: String, description: String, site: Boolean, version: String)
  case class ClusterStatNodesProcessCpu(percent: Int)
  case class ClusterStatNodesProcessOpenFileDescriptors(min: Int, max: Int, avg: Int)
  case class ClusterStatNodesProcess(cpu: ClusterStatNodesProcessCpu, open_file_descriptors: ClusterStatNodesProcessOpenFileDescriptors)
  case class ClusterStatNodesOsMem(total_in_bytes: Long)
  case class ClusterStatNodesOsCpu(count: Int, model: String, mhz: Int, total_sockets: Int, cache_size_in_bytes: Int, vendor: String, cores_per_socket: Int, total_cores: Int)
  case class ClusterStatNodesOs(available_processors: Int, mem: ClusterStatNodesOsMem, cpu: Array[ClusterStatNodesOsCpu])
  case class ClusterStatNodesFs(disk_reads: Int, disk_read_size_in_bytes: Long, total_in_bytes: Long, disk_write_size_in_bytes: Long, free_in_bytes: Long, disk_io_op: Int, disk_writes: Int, available_in_bytes: Long, disk_io_size_in_bytes: Long)
  case class ClusterStatNodes(jvm: ClusterStatNodesJvm, count: ClusterStatNodesCount, plugins: Array[ClusterStatNodesPlugins], versions: Array[String], process: ClusterStatNodesProcess, os: ClusterStatNodesOs, fs: ClusterStatNodesFs)
  case class ClusterStat(cluster_name: String, indices: ClusterStatIndices, timestamp: Long, nodes: ClusterStatNodes, status: String)

  object ClusterStatProtocol extends DefaultJsonProtocol {
    implicit val clusterStatIndicesShardsIndexShardsFormat = jsonFormat3(ClusterStatIndicesShardsIndexShards)
    implicit val clusterStatIndicesShardsIndexPrimariesFormat = jsonFormat3(ClusterStatIndicesShardsIndexPrimaries)
    implicit val clusterStatIndicesShardsIndexReplicationFormat = jsonFormat3(ClusterStatIndicesShardsIndexReplication)
    implicit val clusterStatIndicesShardsIndexFormat = jsonFormat3(ClusterStatIndicesShardsIndex)
    implicit val clusterStatIndicesShardsFormat = jsonFormat4(ClusterStatIndicesShards)
    implicit val clusterStatIndicesFilterCacheFormat = jsonFormat2(ClusterStatIndicesFilterCache)
    implicit val clusterStatIndicesIdCacheFormat = jsonFormat1(ClusterStatIndicesIdCache)
    implicit val clusterStatIndicesDocsFormat = jsonFormat2(ClusterStatIndicesDocs)
    implicit val clusterStatIndicesCompletionFormat = jsonFormat1(ClusterStatIndicesCompletion)
    implicit val clusterStatIndicesStoreFormat = jsonFormat2(ClusterStatIndicesStore)
    implicit val clusterStatIndicesPercolateFormat = jsonFormat6(ClusterStatIndicesPercolate)
    implicit val clusterStatIndicesSegmentsFormat = jsonFormat6(ClusterStatIndicesSegments)
    implicit val clusterStatIndicesFielddataFormat = jsonFormat2(ClusterStatIndicesFielddata)
    implicit val clusterStatIndicesFormat = jsonFormat10(ClusterStatIndices)
    implicit val clusterStatNodesJvmVersionsFormat = jsonFormat5(ClusterStatNodesJvmVersions)
    implicit val clusterStatNodesJvmMemFormat = jsonFormat2(ClusterStatNodesJvmMem)
    implicit val clusterStatNodesJvmFormat = jsonFormat4(ClusterStatNodesJvm)
    implicit val clusterStatNodesCountFormat = jsonFormat5(ClusterStatNodesCount)
    implicit val clusterStatNodesPluginsFormat = jsonFormat6(ClusterStatNodesPlugins)
    implicit val clusterStatNodesProcessCpuFormat = jsonFormat1(ClusterStatNodesProcessCpu)
    implicit val clusterStatNodesProcessOpenFileDescriptorsFormat = jsonFormat3(ClusterStatNodesProcessOpenFileDescriptors)
    implicit val clusterStatNodesProcessFormat = jsonFormat2(ClusterStatNodesProcess)
    implicit val clusterStatNodesOsMemFormat = jsonFormat1(ClusterStatNodesOsMem)
    implicit val clusterStatNodesOsCpuFormat = jsonFormat8(ClusterStatNodesOsCpu)
    implicit val clusterStatNodesOsFormat = jsonFormat3(ClusterStatNodesOs)
    implicit val clusterStatNodesFsFormat = jsonFormat9(ClusterStatNodesFs)
    implicit val clusterStatNodesFormat = jsonFormat7(ClusterStatNodes)
    implicit val clusterStatFormat = jsonFormat5(ClusterStat)
  }
}
